export interface EquipmentItem {
  id: string;
  name: string;
  image: string;
  summary: string;
  muscles: string[];
  videoUrl: string;
  correctForm: string[];
  safetyTips: string[];
  commonMistakes: string[];
  qrCode: string;
}

export const EQUIPMENT_LIST: EquipmentItem[] = [
  {
    id: "bench-press",
    name: "Bench Press",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80",
    summary: "Flat barbell bench for chest, shoulders & triceps. The foundation of upper-body strength training.",
    muscles: ["Chest", "Triceps", "Front Deltoids"],
    videoUrl: "https://www.youtube.com/embed/rT7DgCr-1pg",
    correctForm: [
      "Retract shoulder blades and arch upper back slightly",
      "Grip bar slightly wider than shoulder width",
      "Lower bar to mid-chest with control",
      "Drive through feet and press bar up in slight arc",
    ],
    safetyTips: ["Always use a spotter for heavy sets", "Keep wrists straight", "Never bounce bar off chest"],
    commonMistakes: ["Flaring elbows too wide", "Lifting hips off bench", "Incomplete range of motion"],
    qrCode: "AAMDAR-BENCH-PRESS",
  },
  {
    id: "squat-rack",
    name: "Squat Rack",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80",
    summary: "Heavy-duty power rack for squats, overhead press & rack pulls. Built for serious lifters.",
    muscles: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    videoUrl: "https://www.youtube.com/embed/ultWZbUMPL8",
    correctForm: [
      "Bar rests on upper traps, not neck",
      "Feet shoulder-width, toes slightly out",
      "Descend until thighs are parallel or below",
      "Drive up through mid-foot",
    ],
    safetyTips: ["Set safety bars at appropriate height", "Warm up with empty bar first", "Never round lower back"],
    commonMistakes: ["Knees caving inward", "Heels lifting off ground", "Not hitting depth"],
    qrCode: "AAMDAR-SQUAT-RACK",
  },
  {
    id: "smith-machine",
    name: "Smith Machine",
    image: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=600&q=80",
    summary: "Guided barbell system ideal for controlled squats, presses & lunges with added stability.",
    muscles: ["Full Body", "Quadriceps", "Chest"],
    videoUrl: "https://www.youtube.com/embed/Ajusx3uZ4KU",
    correctForm: [
      "Position body correctly under the bar path",
      "Use full range of motion for each exercise",
      "Lock safety catches before unracking",
    ],
    safetyTips: ["Check safety stoppers are set", "Don't twist body off bar path", "Use clips on weights"],
    commonMistakes: ["Feet too far forward on squats", "Partial reps", "Not using safety catches"],
    qrCode: "AAMDAR-SMITH-MACHINE",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    image: "https://images.unsplash.com/photo-1597452485669-b2090d94691a?w=600&q=80",
    summary: "Cable pulldown station for building a wide, strong back and improving pull-up strength.",
    muscles: ["Latissimus Dorsi", "Biceps", "Rear Deltoids"],
    videoUrl: "https://www.youtube.com/embed/CAwf7n6Luuc",
    correctForm: [
      "Grip bar wider than shoulders",
      "Pull bar to upper chest, squeezing lats",
      "Control the return — don't let weight slam",
    ],
    safetyTips: ["Secure thighs under pad firmly", "Don't pull bar behind neck", "Use controllable weight"],
    commonMistakes: ["Using momentum and swinging", "Leaning too far back", "Not squeezing at bottom"],
    qrCode: "AAMDAR-LAT-PULLDOWN",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80",
    summary: "Plate-loaded leg press for quad & glute development without spinal loading.",
    muscles: ["Quadriceps", "Glutes", "Hamstrings"],
    videoUrl: "https://www.youtube.com/embed/IZxyjW7MPJQ",
    correctForm: [
      "Feet shoulder-width on platform",
      "Lower sled until knees reach ~90°",
      "Press through heels, don't lock knees",
    ],
    safetyTips: ["Never lock knees at top", "Don't let lower back round off pad", "Use safety catches"],
    commonMistakes: ["Going too deep causing back to round", "Locking knees", "Feet placement too high/low"],
    qrCode: "AAMDAR-LEG-PRESS",
  },
  {
    id: "leg-curl",
    name: "Leg Curl Machine",
    image: "https://images.unsplash.com/photo-1434682881908-b43d05f5b870?w=600&q=80",
    summary: "Isolation machine targeting hamstrings for balanced leg development and injury prevention.",
    muscles: ["Hamstrings", "Calves"],
    videoUrl: "https://www.youtube.com/embed/ELOCsoDSmrg",
    correctForm: [
      "Align knee joint with machine pivot",
      "Curl smoothly without hip lift",
      "Squeeze hamstrings at top for 1 second",
    ],
    safetyTips: ["Start with light weight to learn movement", "Don't hyperextend knees", "Control the negative"],
    commonMistakes: ["Lifting hips off pad", "Using momentum", "Incomplete range of motion"],
    qrCode: "AAMDAR-LEG-CURL",
  },
  {
    id: "cable-machine",
    name: "Cable Machine",
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80",
    summary: "Dual adjustable pulleys for endless exercise variety — flyes, rows, curls & more.",
    muscles: ["Varies by exercise"],
    videoUrl: "https://www.youtube.com/embed/GAiRjF44oJg",
    correctForm: [
      "Set pulley at appropriate height",
      "Control both concentric and eccentric phases",
      "Squeeze target muscle at peak contraction",
    ],
    safetyTips: ["Check cable for fraying", "Don't release weight stack suddenly", "Use correct attachment"],
    commonMistakes: ["Using body momentum", "Wrong pulley height", "Letting weights crash"],
    qrCode: "AAMDAR-CABLE-MACHINE",
  },
  {
    id: "dumbbell-rack",
    name: "Dumbbell Station",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80",
    summary: "Full dumbbell rack from 2.5kg to 50kg for versatile free-weight training.",
    muscles: ["Full Body"],
    videoUrl: "https://www.youtube.com/embed/6kALZikXxLc",
    correctForm: [
      "Choose weight you can control with proper form",
      "Keep core braced throughout",
      "Return dumbbells to rack safely after set",
    ],
    safetyTips: ["Don't drop dumbbells", "Clear space before lifting", "Use collars on adjustable DBs"],
    commonMistakes: ["Swinging weights", "Weight too heavy", "Dropping from height"],
    qrCode: "AAMDAR-DUMBBELL-STATION",
  },
  {
    id: "treadmill",
    name: "Treadmill",
    image: "https://images.unsplash.com/photo-1576678927486-cc907957088c?w=600&q=80",
    summary: "Commercial-grade treadmills for cardio, HIIT intervals & incline walking sessions.",
    muscles: ["Cardiovascular", "Legs", "Core"],
    videoUrl: "https://www.youtube.com/embed/54x2WF1_Suc",
    correctForm: [
      "Start at slow speed and gradually increase",
      "Land mid-foot, not on heels",
      "Keep upright posture, avoid holding rails",
    ],
    safetyTips: ["Use safety clip attached to clothing", "Step off belt before stopping", "Stay hydrated"],
    commonMistakes: ["Holding handrails while running", "Overstriding", "Skipping warm-up"],
    qrCode: "AAMDAR-TREADMILL",
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    image: "https://images.unsplash.com/photo-1540497077202-7a8a399fb6be?w=600&q=80",
    summary: "Full-body cardio rower engaging 86% of muscles. Low-impact, high-calorie burn.",
    muscles: ["Back", "Legs", "Arms", "Core"],
    videoUrl: "https://www.youtube.com/embed/zQ82RYIFLN8",
    correctForm: [
      "Drive with legs first, then lean back, then pull arms",
      "Return in reverse order: arms, body, legs",
      "Maintain consistent stroke rate",
    ],
    safetyTips: ["Secure feet in straps", "Don't round lower back at catch", "Start with 5-min sessions"],
    commonMistakes: ["Arms pulling too early", "Rounded back", "Rushing the recovery"],
    qrCode: "AAMDAR-ROWING-MACHINE",
  },
  {
    id: "shoulder-press",
    name: "Shoulder Press Machine",
    image: "https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=600&q=80",
    summary: "Seated press machine for safe, targeted deltoid and tricep development.",
    muscles: ["Shoulders", "Triceps", "Upper Chest"],
    videoUrl: "https://www.youtube.com/embed/WvLMauqrnK8",
    correctForm: [
      "Adjust seat so handles align with shoulders",
      "Press straight up without arching back",
      "Lower to ear level with control",
    ],
    safetyTips: ["Don't lock elbows at top", "Keep back against pad", "Use manageable weight"],
    commonMistakes: ["Excessive back arch", "Pressing too far forward", "Bouncing at bottom"],
    qrCode: "AAMDAR-SHOULDER-PRESS",
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl Bench",
    image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80",
    summary: "Angled pad isolates biceps by eliminating momentum for peak arm development.",
    muscles: ["Biceps", "Forearms"],
    videoUrl: "https://www.youtube.com/embed/fIWP-FRF9VE",
    correctForm: [
      "Armpits rest at top of pad",
      "Curl with full range — full extension to contraction",
      "Lower weight slowly on the negative",
    ],
    safetyTips: ["Don't hyperextend elbows at bottom", "Use EZ bar for wrist comfort", "Start light"],
    commonMistakes: ["Lifting elbows off pad", "Swinging weight", "Partial reps"],
    qrCode: "AAMDAR-PREACHER-CURL",
  },
];
